"""
===========================================================
Project : Sentinel AI
Module  : HTML Report
File ID : REPORT-HTML-001
Version : 1.0.0
===========================================================

Description:
Generates a professional HTML security report from
analysis results.

===========================================================
"""

from __future__ import annotations


class HTMLReport:
    """
    Generates HTML reports.
    """

    # ======================================================
    # Generate Report
    # ======================================================

    def generate(
        self,
        analysis: dict,
    ) -> str:
        """
        Generate HTML report.

        Returns:
            HTML string
        """

        summary = analysis.get("summary", {})

        findings = analysis.get("findings", [])

        recommendations = analysis.get(
            "recommendations",
            [],
        )

        html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8">

<title>Sentinel AI Report</title>

<style>

body {{

font-family: Arial, Helvetica, sans-serif;

margin:40px;

background:#f5f5f5;

}}

.container {{

background:white;

padding:30px;

border-radius:10px;

}}

table {{

width:100%;

border-collapse:collapse;

margin-top:20px;

}}

th, td {{

border:1px solid #cccccc;

padding:10px;

text-align:left;

}}

th {{

background:#eeeeee;

}}

h1,h2 {{

color:#222;

}}

.high {{

color:red;

font-weight:bold;

}}

.medium {{

color:orange;

font-weight:bold;

}}

.low {{

color:green;

font-weight:bold;

}}

.info {{

color:blue;

font-weight:bold;

}}

</style>

</head>

<body>

<div class="container">

<h1>Sentinel AI Security Report</h1>

<hr>

<h2>Target</h2>

<p>{analysis.get("target","Unknown")}</p>

<h2>Executive Summary</h2>

<ul>

<li><strong>Risk Score:</strong> {summary.get("score",0)}/100</li>

<li><strong>Risk Level:</strong> {summary.get("risk_level","Unknown")}</li>

<li><strong>Total Findings:</strong> {summary.get("total_findings",0)}</li>

</ul>

<h2>Findings</h2>

<table>

<tr>

<th>Severity</th>

<th>Title</th>

</tr>
"""
        # ======================================================
        # Findings
        # ======================================================

        for finding in findings:

            if hasattr(finding, "severity"):

                severity = finding.severity
                title = finding.title

            else:

                severity = finding.get("severity", "Info")
                title = finding.get("title", "Unknown")

            css = severity.lower()

            html += f"""
<tr>
<td class="{css}">{severity}</td>
<td>{title}</td>
</tr>
"""

        html += """
</table>

<h2>Recommendations</h2>

<table>

<tr>

<th>Priority</th>

<th>Recommendation</th>

</tr>
"""

        # ======================================================
        # Recommendations
        # ======================================================

        for item in recommendations:

            priority = item.get(
                "priority",
                "Unknown",
            )

            recommendation = item.get(
                "recommendation",
                item.get(
                    "title",
                    "",
                ),
            )

            html += f"""
<tr>
<td>{priority}</td>
<td>{recommendation}</td>
</tr>
"""

        # ======================================================
        # Footer
        # ======================================================

        html += f"""

</table>

<hr>

<p>

Generated by
<strong>Sentinel AI</strong>

</p>

</div>

</body>

</html>

"""

        return html


# ===========================================================
# Temporary Test
# ===========================================================

if __name__ == "__main__":

    report = HTMLReport()

    sample = {
        "target": "https://bugcrowd.com",
        "summary": {
            "score": 68,
            "risk_level": "High",
            "total_findings": 3,
        },
        "findings": [
            {
                "severity": "High",
                "title": "Sensitive Secret Found in JavaScript",
            },
            {
                "severity": "Medium",
                "title": "Missing Content Security Policy",
            },
            {
                "severity": "Info",
                "title": "Technology Identified",
            },
        ],
        "recommendations": [
            {
                "priority": "High",
                "recommendation": "Remove exposed secrets from JavaScript.",
            },
            {
                "priority": "Medium",
                "recommendation": "Configure a strict Content-Security-Policy.",
            },
        ],
    }

    html = report.generate(sample)

    print()

    print("=" * 60)

    print("HTML Report")

    print("=" * 60)

    print()

    print(html[:1000])

    print()

    print("... HTML Generated Successfully ...")
